apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: mocha
  name: mocha
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mocha
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: mocha
    spec:
      containers:
        - args:
            - http://example/test
          env:
            - name: WAIT_FOR_HOSTS
              value: example:80
          image: blueimp/mocha-chrome
          name: mocha
          resources: {}
      restartPolicy: Always
status: {}
