apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: wdio
  name: wdio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wdio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: wdio
    spec:
      containers:
        - env:
            - name: MACOS_ASSETS_DIR
              value: /home/airobot/Kubernetes/frontend/wdio/assets/
            - name: WAIT_FOR_HOSTS
              value: chromedriver:4444 geckodriver:4444 example:80
          image: blueimp/wdio
          name: wdio
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: wdio-claim0
              readOnly: true
            - mountPath: /app/reports
              name: wdio-claim1
            - mountPath: /tmp
              name: wdio-tmpfs0
      restartPolicy: Always
      volumes:
        - name: wdio-claim0
          persistentVolumeClaim:
            claimName: wdio-claim0
            readOnly: true
        - name: wdio-claim1
          persistentVolumeClaim:
            claimName: wdio-claim1
        - emptyDir:
            medium: Memory
          name: wdio-tmpfs0
status: {}
