apiVersion: v1
kind: Pod
metadata:
  name: dope-pod
  labels:
    app: ubuntu
spec:
  containers:
  - name: dope-pod
    image: jason134017/dope:latest
    command: ["/bin/sleep", "3650d"]
    ports:
      - containerPort: 11311
    #containerPort: 11311
    resources:
        limits:
          memory: "2048Mi"
          #cpu: "500M"
          #nvidia.com/gpu: 1
  imagePullSecrets:
  - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: ros-service
spec:
  selector:
    app: dope-pod
  ports:
  - port: 11311
    targetPort: 11311
    #nodeport:


